services:
  ambev.developerevaluation.database:
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: local_development_password
    ports:
      - "5432:5432"
    volumes:
      - developer_evaluation_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d developer_evaluation"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  developer_evaluation_data:
